### ISSUE TITLE
Could you please help me add the retweeter api?

### ISSUE THREAD

**Issue by wade-liwei** [imperatrona/twitter-scraper#12]
I added the following codes for the retweeter API. 
After I used the retweeter API once with account's cookie, Twitter lock my account.

Could you please help me add the retweeter api and tell me the reason?

**Comment by wade-liwei** [comment]
func (s *Scraper) RetweetsUsers(tweetId string, maxTweetsNbr int, cursor string) ([]*Profile, string, error) {

	if maxTweetsNbr > 200 {
		maxTweetsNbr = 200
	}

	req, err := s.newRequest("Get", "https://twitter.com/i/api/graphql/_D6CD5GX3VTL4ZzoAjJjGA/Retweeters")

	if err != nil {
		return nil, "", err
	}

	req.Header.Set("content-type", "application/json")

	variables := map[string]interface{}{
		"tweetId":                tweetId,
		"count":                  maxTweetsNbr,
		"includePromotedContent": false,
	}

	features := map[string]interface{}{
		"rweb_tipjar_consumption_enabled":                                         true,
		"responsive_web_graphql_exclude_directive_enabled":                        true,
		"verified_phone_label_enabled":                                            false,
		"creator_subscriptions_tweet_preview_api_enabled":                         true,
		"responsive_web_graphql_timeline_navigation_enabled":                      true,
		"responsive_web_graphql_skip_user_profile_image_extensions_enabled":       false,
		"communities_web_enable_tweet_community_results_fetch":                    true,
		"c9s_tweet_anatomy_moderator_badge_enabled":                               true,
		"articles_preview_enabled":                                                true,
		"tweetypie_unmention_optimization_enabled":                                true,
		"responsive_web_edit_tweet_api_enabled":                                   true,
		"graphql_is_translatable_rweb_tweet_is_translatable_enabled":              true,
		"view_counts_everywhere_api_enabled":                                      true,
		"longform_notetweets_consumption_enabled":                                 true,
		"responsive_web_twitter_article_tweet_consumption_enabled":                true,
		"tweet_awards_web_tipping_enabled":                                        false,
		"creator_subscriptions_quote_tweet_preview_enabled":                       false,
		"freedom_of_speech_not_reach_fetch_enabled":                               true,
		"standardized_nudges_misinfo":                                             true,
		"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": true,
		"rweb_video_timestamps_enabled":                                           true,
		"longform_notetweets_rich_text_read_enabled":                              true,
		"longform_notetweets_inline_media_enabled":                                true,
		"responsive_web_enhance_cards_enabled":                                    false,
	}

	if cursor != "" {
		variables["cursor"] = cursor
	}

	query := url.Values{}
	query.Set("variables", mapToJSONString(variables))
	query.Set("features", mapToJSONString(features))
	req.URL.RawQuery = query.Encode()

	var timeline RetweetTimeLine

	err = s.RequestAPI(req, &timeline)
	if err != nil {
		return nil, "", err
	}

	users, nextCursor := timeline.parseUsers()

	if strings.HasPrefix(nextCursor, "0|") {
		nextCursor = ""
	}

	fmt.Println("retweet task", "len(users)", len(users), "nextCursor", nextCursor)

	return users, nextCursor, nil
}

**Comment by wade-liwei** [comment]
I guess the problem is 	"includePromotedContent": false,
but I do not have a account to verify.

**Comment by wade-liwei** [comment]
I have been managing 20 accounts per IP address without receiving a ban for several months.

How many API do you use?

**Comment by imperatrona** [comment]
hi @wade-liwei! added `GetTweetRetweeters` method.
how often you did requests? make sure you set at least 5 seconds between requests `scraper.WithDelay(5)`

my telegram bot still using the same 20 accounts for average ~3800-4000 requests per hour (wich is 50 request per 15 min per account). it's a year now without any account banned.

**Comment by wade-liwei** [comment]
Thank you so much.
But my boss ask me to use the twitter API(the paied API).
So I have to give up your solution again. (we need to request many API interfaces, not only one)

Anyway, thank you.

**Comment by wade-liwei** [comment]
Thank you so much.
But my boss ask me to use the twitter API(the paied API).
So I have to give up your solution again. (we need to request many API interfaces, not only one)

Anyway, thank you.
