### ISSUE TITLE
Auth error (353): This request requires a matching csrf cookie and header.

### ISSUE THREAD

**Issue by M1chlCZ** [imperatrona/twitter-scraper#16]
I am suddenly getting this error, which I don't know how to fix, this is relevant part of the code. So if you could help me with that, I am going to be `glad.`

```
	scraper := twitterscraper.New()
	loggedIn := false
	f, err := os.Open("cookies.json")
	if err == nil {
		defer f.Close()
		var cookies []*http.Cookie
		err := json.NewDecoder(f).Decode(&cookies)
		if err == nil {
			scraper.SetCookies(cookies)
			loggedIn = scraper.IsLoggedIn()
		}
	}
	if !loggedIn {
		_ = os.Remove("cookies.json")
		err := scraper.Login("usr", "pass")
		if err != nil {
			utils.WrapErrorLog(err.Error() + " 1")
			return
		}
		cookies := scraper.GetCookies()
		js, _ := json.Marshal(cookies)
		f, _ := os.Create("cookies.json")
		_, err = f.Write(js)
		if err != nil {
			utils.WrapErrorLog(err.Error() + " 2")
			return
		}
	}
```

**Comment by teslashibe** [comment]
We would love to help and contribute. Please share and we can collaborate

**Comment by teslashibe** [comment]
@imperatrona I wrote a fix for this today and it works. We should collaborate on maintaining this package together. We are going to fork and maintain the fork carefully. We are also going to refactor the code so it's not a flat package which will make it easier to maintain. We are an open source company and have resources to maintain this consistently. Why done we team up and build a community around a stable go package? We will make sure it's maintained in a daily basis and we can collaborate. 

I love the work you have done to iterate on n0madics work. 

I sent you a twitter dm let's chat there.

**Comment by imperatrona** [comment]
@teslashibe sure i'm open to chat:)

**Comment by rectid** [comment]
@teslashibe Hello! You wrote that you were able to fix the authentication. Can you upload this solution to your fork/make a pull request in this repo? I have been racking my brains over this problem for several days, I would be very grateful to you.

**Comment by M1chlCZ** [comment]
> @rectid i haven't check but here is their fork: [masa-finance/masa-twitter-scraper@`feat-fix-login`](https://github.com/masa-finance/masa-twitter-scraper/tree/feat-fix-login?rgh-link-date=2024-09-19T13%3A04%3A22Z)

Just want to confirm, that these changes are working, so if someone can incorporate them here, it would be nice.

**Comment by imperatrona** [comment]
@M1chlCZ thank you i'll check them and add them here in couple days:)

**Comment by imperatrona** [comment]
hi @M1chlCZ i've add changes, can you please check if latest version fixes this error for you?

**Comment by M1chlCZ** [comment]
It did, thank you!

**Comment by ealmuina** [comment]
@imperatrona This is still happening to me after updating to 0.0.13 😔

**Comment by imperatrona** [comment]
@ealmuina do you get same 353 error?

**Comment by ealmuina** [comment]
> @ealmuina do you get same 353 error?

Yes, same 353: This request requires a matching csrf cookie and header

**Comment by imperatrona** [comment]
@ealmuina thats probably my fault, can you check v0.0.14?
```bash
go get -u github.com/imperatrona/twitter-scraper@v0.0.14
```

**Comment by ealmuina** [comment]
Awesome! That one does solve it for me. Thanks a lot!!

**Comment by imperatrona** [comment]
@ealmuina Thank you so much for helping me!
