### ISSUE TITLE
getLatestTweet and getTweets not showing results

### ISSUE THREAD

**Issue by im-kent** [imperatrona/twitter-scraper#17]
Does anyone experience issues with getLatestTweet and getTweets showing no results when the user clearly has posts? I am not authenticated when I make these function calls.

I attempted it with username: devjumzzz and while the user has posts on their twitter account, I am getting no results when running these two functions.

Note, I am using a JS implementation of the twitter-scraper codebase, which may account for some differences, but I am thinking it may be due to something else.

Thank you

**Comment by imperatrona** [comment]
Twitter removed ability to see user feed without auth, you can check by open any profile in browser incognito mode. It's making response to `UserTweets` but return result with no tweets, so it doesn't throw any error.

**Comment by im-kent** [comment]
Thank you for the quick response. Since authentication is required, it seems that rate limits will be more impactful. Do you happen to know what the rate limits are for calls to the API for UserTweets?

**Comment by imperatrona** [comment]
@im-kent maximum 150 requests per 15 minutes though i recommend use less around 100 request should be safe per account

**Comment by im-kent** [comment]
Thank you!
