### ISSUE TITLE
Updating the api code in GetTweetReplies

### ISSUE THREAD

**Issue by MrNomad123** [imperatrona/twitter-scraper#18]
The endpoint in GetTweetReplies method is `GET  https://twitter.com/i/api/graphql/ldqoq5MmFHN1FhMGvzC9Jg/TweetDetail`. This returns 404 to me. Upon inspecting in brower the request was made with a different code (in place of `ldqoq5MmFHN1FhMGvzC9Jg`). Do we know what decides the value of this code? Or at least I think we should make it configurable. I can do this...but I am new to golang and will take some time catching up.

**Comment by imperatrona** [comment]
@MrNomad123 checked right now and endpoint works, this hash is id for specific revision of endpoint so if you change this hash to newer/older the response may be diffrently structured and wouldn't be parsed correctly. some endpoint hashes in this codebase is 2-3 years old and works perfectly twitter don't expire them

can you provide tweet url that you trying to fetch?

![Screenshot 2024-09-28 at 15 23 34](https://github.com/user-attachments/assets/ff0cb501-8df7-4fed-9571-a14a60689e0a)

**Comment by MrNomad123** [comment]
This is the tweet id I am trying to fetch: 1839894571054182414

**Comment by imperatrona** [comment]
@MrNomad123 works for me. did you set your auth credentials before making request?

![Screenshot 2024-10-02 at 22 02 47](https://github.com/user-attachments/assets/2eaedd16-ce74-4c1c-8b0b-d01e231a816d)

**Comment by MrNomad123** [comment]
Yeah...works fine. Not sure what the issue was. Anyways, thanks for the help!
