### ISSUE TITLE
Login(username, password) returns no error but IsLoggedIn() returns false

### ISSUE THREAD

**Issue by ealmuina** [imperatrona/twitter-scraper#27]
I'm having this issue since yesterday. After calling `err := scrapper.Login(username, password)`, I see `err` is `nil`. But then when I check `scrapper.IsLoggedIn()` it returns `false`.

I have tried to call `scraper.ClearCookies()` just before the login attempt, just in case it was a problem with older cookies. But that doesn't solve it, nor running the program from scratch.

**Comment by ealmuina** [comment]
I think it was an issue with `https://api.twitter.com/1.1/account/verify_credentials.json` on Twitter's side. It fixed itself after some hours. I'll close this ticket for now and reopen it if it happens again.

**Comment by ealmuina** [comment]
The problem is back. This is the response the library gets from `https://api.twitter.com/1.1/account/verify_credentials.json`, in case it helps:

```
response status 403 Forbidden: {"errors":[{"message":"Your credentials do not allow access to this resource","code":37}]}
```

**Comment by thewh1teagle** [comment]
@ealmuina 

I experience similar issue. with api.twitter.com it returns 404 error. with x.com it returns the same error as yours

**Comment by ealmuina** [comment]
As I mitigation, for now I'm running fine by just skipping the call to `scrapper.IsLoggedIn()` and simply checking if `scrapper.Login(username, password)` doesn't return any error.

**Comment by thewh1teagle** [comment]
> the problem is back. This is the response the library gets from `https://api.twitter.com/1.1/account/verify_credentials.json`, in case it helps:

My response:

```console
Login failed: response status 404 Not Found: {"errors":[{"message":"Sorry, that page does not exist","code":34}]}
```

**Comment by thewh1teagle** [comment]
I found why it failed.
We need `x-client-transaction-id` as well in each API request. it's different in each request. any idea how to generate it?

**Comment by cmj** [comment]
I've been playing around using shell scripts to make it easier for me to quickly understand what is and isn't needed. This seems to still work for me today: 

https://github.com/cmj/twitter-tools/blob/4a2743351ad83ec7de817ad2ac36575cd19fda88/twitter-cookie.sh#L32-L33

Just a user-generated 94 character string works in this example. I'm not entirely sure this is the solution, but worth a try.

**Comment by thewh1teagle** [comment]
> The bearerToken needs to be changed. Something like this should work...
> 
> https://gist.github.com/cmj/8ada29ebbf202b971e7336df9dc1e81d

that worked! changing the bearer token to:

```console
AAAAAAAAAAAAAAAAAAAAAG5LOQEAAAAAbEKsIYYIhrfOQqm4H8u7xcahRkU%3Dz98HKmzbeXdKqBfUDmElcqYl0cmmKY9KdS2UoNIz3Phapgsowi
```

Allows sending requests without `x-client-transaction-id`

**Comment by cmj** [comment]
There seems to be a rate-limit issue with that bearer token. The one in the patch I shared is limited at 75.

We need to use this token which has an `x-rate-limit-limit: 2000`

```"AAAAAAAAAAAAAAAAAAAAAFQODgEAAAAAVHTp76lzh3rFzcHbmHVvQxYYpTw%3DckAlMINMjmCwxUcaXbAN4XqJVdgMJaHqNOFgPMK0zN1qLqLQCF"```

Sorry for not checking this first.
