### ISSUE TITLE
401 Unauthorized: {"errors":[{"message":"Could not authenticate you","code":32}]}

### ISSUE THREAD

**Issue by hello-world-1989** [imperatrona/twitter-scraper#29]
```
func main() {
	scraper := twitterscraper.New()
	scraper.SetAuthToken(twitterscraper.AuthToken{Token: "auth_token", CSRFToken: "ct0"})

	err := scrapper.Login(username, password)
        // err := scrapper.Login(username, password, email) 401 error
	status1 := scraper.IsLoggedIn()

	fmt.Println(err) //response status 401 Unauthorized: {"errors":[{"message":"Could not authenticate you","code":32}]}
	fmt.Println(status1) //false
}
```

**Comment by hello-world-1989** [comment]
Does anyone have this issue? Cannot login

**Comment by imperatrona** [comment]
@hello-world-1989 which method get you this error?

**Comment by hello-world-1989** [comment]
> @hello-world-1989 which method get you this error?

scrapper.Login(username, password).

Thank you!

func main() {
	scraper := twitterscraper.New()
	scraper.SetAuthToken(twitterscraper.AuthToken{Token: "auth_token", CSRFToken: "ct0"})

	err := scrapper.Login(username, password)
	status1 := scraper.IsLoggedIn()

	fmt.Println(err) //response status 401 Unauthorized: {"errors":[{"message":"Could not authenticate you","code":32}]}
	fmt.Println(status1) //false
}

**Comment by hello-world-1989** [comment]
Removed this line and change another X account works

`scraper.SetAuthToken(twitterscraper.AuthToken{Token: "auth_token", CSRFToken: "ct0"})`
